<template>
  <div class="wrapper">
    <div class="content">
      <div>asf1</div>
      <div>asf2</div>
      <div>asf3</div>
      <div>asf4</div>
      <div>asf5</div>
      <div>asf6</div>
      <div>asf7</div>
      <div>asf8</div>
      <div>asf9</div>
      <div>asf10</div>
      <div>asf11</div>
      <div>asf12</div>
      <div>asf13</div>
      <div>asf14</div>
      <div>asf15</div>
      <div>asf16</div>
      <div>asf17</div>
      <div>asf18</div>
      <div>asf19</div>
      <div>asf20</div>
      <div>asf21</div>
      <div>asf22</div>
      <div>asf23</div>
      <div>asf24</div>
      <div>asf25</div>
      <div>asf26</div>
      <div>asf27</div>
      <div>asf28</div>
      <div>asf29</div>
      <div>asf30</div>
      <div>asf1</div>
      <div>asf2</div>
      <div>asf3</div>
      <div>asf4</div>
      <div>asf5</div>
      <div>asf6</div>
      <div>asf7</div>
      <div>asf8</div>
      <div>asf9</div>
      <div>asf10</div>
      <div>asf11</div>
      <div>asf12</div>
      <div>asf13</div>
      <div>asf14</div>
      <div>asf15</div>
      <div>asf16</div>
      <div>asf17</div>
      <div>asf18</div>
      <div>asf19</div>
      <div>asf20</div>
      <div>asf21</div>
      <div>asf22</div>
      <div>asf23</div>
      <div>asf24</div>
      <div>asf25</div>
      <div>asf26</div>
      <div>asf27</div>
      <div>asf28</div>
      <div>asf29</div>
      <div>asf30</div>
      <div>asf1</div>
      <div>asf2</div>
      <div>asf3</div>
      <div>asf4</div>
      <div>asf5</div>
      <div>asf6</div>
      <div>asf7</div>
      <div>asf8</div>
      <div>asf9</div>
      <div>asf10</div>
      <div>asf11</div>
      <div>asf12</div>
      <div>asf13</div>
      <div>asf14</div>
      <div>asf15</div>
      <div>asf16</div>
      <div>asf17</div>
      <div>asf18</div>
      <div>asf19</div>
      <div>asf20</div>
      <div>asf21</div>
      <div>asf22</div>
      <div>asf23</div>
      <div>asf24</div>
      <div>asf25</div>
      <div>asf26</div>
      <div>asf27</div>
      <div>asf28</div>
      <div>asf29</div>
      <div>asf30</div>
      <div>asf1</div>
      <div>asf2</div>
      <div>asf3</div>
      <div>asf4</div>
      <div>asf5</div>
      <div>asf6</div>
      <div>asf7</div>
      <div>asf8</div>
      <div>asf9</div>
      <div>asf10</div>
      <div>asf11</div>
      <div>asf12</div>
      <div>asf13</div>
      <div>asf14</div>
      <div>asf15</div>
      <div>asf16</div>
      <div>asf17</div>
      <div>asf18</div>
      <div>asf19</div>
      <div>asf20</div>
      <div>asf21</div>
      <div>asf22</div>
      <div>asf23</div>
      <div>asf24</div>
      <div>asf25</div>
      <div>asf26</div>
      <div>asf27</div>
      <div>asf28</div>
      <div>asf29</div>
      <div>asf30</div>
      <div>asf1</div>
      <div>asf2</div>
      <div>asf3</div>
      <div>asf4</div>
      <div>asf5</div>
      <div>asf6</div>
      <div>asf7</div>
      <div>asf8</div>
      <div>asf9</div>
      <div>asf10</div>
      <div>asf11</div>
      <div>asf12</div>
      <div>asf13</div>
      <div>asf14</div>
      <div>asf15</div>
      <div>asf16</div>
      <div>asf17</div>
      <div>asf18</div>
      <div>asf19</div>
      <div>asf20</div>
      <div>asf21</div>
      <div>asf22</div>
      <div>asf23</div>
      <div>asf24</div>
      <div>asf25</div>
      <div>asf26</div>
      <div>asf27</div>
      <div>asf28</div>
      <div>asf29</div>
      <div>asf30</div>
      <div>asf1</div>
      <div>asf2</div>
      <div>asf3</div>
      <div>asf4</div>
      <div>asf5</div>
      <div>asf6</div>
      <div>asf7</div>
      <div>asf8</div>
      <div>asf9</div>
      <div>asf10</div>
      <div>asf11</div>
      <div>asf12</div>
      <div>asf13</div>
      <div>asf14</div>
      <div>asf15</div>
      <div>asf16</div>
      <div>asf17</div>
      <div>asf18</div>
      <div>asf19</div>
      <div>asf20</div>
      <div>asf21</div>
      <div>asf22</div>
      <div>asf23</div>
      <div>asf24</div>
      <div>asf25</div>
      <div>asf26</div>
      <div>asf27</div>
      <div>asf28</div>
      <div>asf29</div>
      <div>asf30</div>
      <div>asf1</div>
      <div>asf2</div>
      <div>asf3</div>
      <div>asf4</div>
      <div>asf5</div>
      <div>asf6</div>
      <div>asf7</div>
      <div>asf8</div>
      <div>asf9</div>
      <div>asf10</div>
      <div>asf11</div>
      <div>asf12</div>
      <div>asf13</div>
      <div>asf14</div>
      <div>asf15</div>
      <div>asf16</div>
      <div>asf17</div>
      <div>asf18</div>
      <div>asf19</div>
      <div>asf20</div>
      <div>asf21</div>
      <div>asf22</div>
      <div>asf23</div>
      <div>asf24</div>
      <div>asf25</div>
      <div>asf26</div>
      <div>asf27</div>
      <div>asf28</div>
      <div>asf29</div>
      <div>asf30</div>
      <div>asf1</div>
      <div>asf2</div>
      <div>asf3</div>
      <div>asf4</div>
      <div>asf5</div>
      <div>asf6</div>
      <div>asf7</div>
      <div>asf8</div>
      <div>asf9</div>
      <div>asf10</div>
      <div>asf11</div>
      <div>asf12</div>
      <div>asf13</div>
      <div>asf14</div>
      <div>asf15</div>
      <div>asf16</div>
      <div>asf17</div>
      <div>asf18</div>
      <div>asf19</div>
      <div>asf20</div>
      <div>asf21</div>
      <div>asf22</div>
      <div>asf23</div>
      <div>asf24</div>
      <div>asf25</div>
      <div>asf26</div>
      <div>asf27</div>
      <div>asf28</div>
      <div>asf29</div>
      <div>asf30</div>
      <div>asf1</div>
      <div>asf2</div>
      <div>asf3</div>
      <div>asf4</div>
      <div>asf5</div>
      <div>asf6</div>
      <div>asf7</div>
      <div>asf8</div>
      <div>asf9</div>
      <div>asf10</div>
      <div>asf11</div>
      <div>asf12</div>
      <div>asf13</div>
      <div>asf14</div>
      <div>asf15</div>
      <div>asf16</div>
      <div>asf17</div>
      <div>asf18</div>
      <div>asf19</div>
      <div>asf20</div>
      <div>asf21</div>
      <div>asf22</div>
      <div>asf23</div>
      <div>asf24</div>
      <div>asf25</div>
      <div>asf26</div>
      <div>asf27</div>
      <div>asf28</div>
      <div>asf29</div>
      <div>asf30</div>
    </div>
  </div>
</template>

<script>
  import BScroll from 'better-scroll'

  export default {
    name: "Category",
    data() {
      return {
        scroll:null
      }
    },
    mounted() {
      this.scroll = new BScroll(document.querySelector('.wrapper'),{
        prodeType: 3
      })

      this.scroll.on('scroll',(position) => {
        console.log(position);
      })

      this.scroll.on('pullingUp',() => {
        console.log('上拉加载更多');

        setTimeout(() => {
          this.scroll.finishPullUp()
        },1000)
      })
    }
  }
</script>

<style scoped>
  .wraper {
    height: 150px;
    background-color: red;

    /*overflow: hidden;*/
  }

</style>
